### ISSUE TITLE
Unhandled promise rejection could occur if this call fails

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [dec112/ng112-js#1]
https://github.com/dec112/ng112-js/blob/a548d41851166d30d70908ffe56b256a0ac3e7a2/src/namespaces/emergency.ts#L152

If this call fails, there is no promise handling. And it can fail if no location is provided

**Comment by gebsl** [comment]
Thanks for the hint, should be fixed with version 0.11.2.
